In [9]:
from google.colab import files
uploaded = files.upload()

Saving productsfull2.csv to productsfull2.csv

In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('productsfull2.csv')

In [12]:
df.head()

,colorname,desc2,description,fit,fitinfo,fulldescription,itemid,name,url
0,[],[],"[""The world's #1-selling hunting knife in its ...",[],[],"[""The world's #1-selling hunting knife in its ...",['219529'],Buck 110 Folding Hunter's Knife,https://www.llbean.com/llb/shop/38592?page=buc...
1,"['Bright Sapphire', 'Cactus', 'Night', 'Teal S...",[],"[""We've combined the freedom of a sandal with ...",[],['Half sizes order down.'],"[""We've combined the freedom of a sandal with ...",['504069'],Kids' Explorer Sandals,https://www.llbean.com/llb/shop/120346?page=ki...
2,['Mossy Oak Country'],"[""Maine State Game Wardens are the pinnacle of...","[""This is the ultimate sportsman's day pack. D...",[],[],"[""This is the ultimate sportsman's day pack. D...",['505356'],"Maine Warden's Day Pack, Camo",https://www.llbean.com/llb/shop/121924?page=ma...
3,['Owl'],[],['These fur-ocious kids’ animal slippers will ...,[],"['Half sizes order up.', 'Sized for toddlers.']",['These fur-ocious kids’ animal slippers will ...,['219943'],Toddlers' Animal Paws Slippers,https://www.llbean.com/llb/shop/38106?page=tod...
4,['Dark Gray Multi'],[],['Our Baby Bogs set the standard in toddlers’ ...,[],[],['Our Baby Bogs set the standard in toddlers’ ...,['306187'],"Toddlers' Baby Bogs Boots, Classic Dino",https://www.llbean.com/llb/shop/118942?page=to...

In [13]:
df.shape

(24714, 9)

In [14]:
df.columns

Index(['colorname', 'desc2', 'description', 'fit', 'fitinfo',
       'fulldescription', 'itemid', 'name', 'url'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24714 entries, 0 to 24713
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   colorname        24714 non-null  object
 1   desc2            24714 non-null  object
 2   description      24714 non-null  object
 3   fit              24714 non-null  object
 4   fitinfo          24714 non-null  object
 5   fulldescription  24714 non-null  object
 6   itemid           24714 non-null  object
 7   name             24714 non-null  object
 8   url              24714 non-null  object
dtypes: object(9)
memory usage: 1.7+ MB

In [16]:
(df == "[]").sum()

colorname            616
desc2              18207
description          286
fit                21319
fitinfo            11382
fulldescription        0
itemid              7432
name                   0
url                    0
dtype: int64

In [17]:
df = df[['name','fulldescription','colorname']]

In [23]:
df

,name,fulldescription,colorname
0,Buck 110 Folding Hunter's Knife,"[""The world's #1-selling hunting knife in its ...",unknown
1,Kids' Explorer Sandals,"[""We've combined the freedom of a sandal with ...","['Bright Sapphire', 'Cactus', 'Night', 'Teal S..."
2,"Maine Warden's Day Pack, Camo","[""This is the ultimate sportsman's day pack. D...",['Mossy Oak Country']
3,Toddlers' Animal Paws Slippers,['These fur-ocious kids’ animal slippers will ...,['Owl']
4,"Toddlers' Baby Bogs Boots, Classic Dino",['Our Baby Bogs set the standard in toddlers’ ...,['Dark Gray Multi']
...,...,...,...
24709,Polar Fleece Blanket,"[""We made this lightweight everyday blanket fr...","['Boulder', 'Cream', 'Desert Sage', 'Mariner B..."
24710,Border Floral Quilt Collection,['Beautiful flowers bloom across the inside of...,['Multi']
24711,Heated Blanket,['Our amazingly plush blanket teams up with th...,['Cream']
24712,Maine-Made Cotton Twill Blanket,['Crafted from cotton twill for a beautiful dr...,"['Bluegrass', 'Heather Gray', 'Mariner Blue', ..."
24713,"Maine-Made Cotton Blanket, Stripe",['This L.L.Bean exclusive Maine blanket is cra...,"['Mariner Blue', 'Sea Salt', 'Gray Heather/Cre..."

In [19]:
df.replace("[]",np.nan,inplace=True)

In [20]:
df=df.dropna(subset=['fulldescription'])

In [22]:
df['colorname'].fillna('unknown',inplace=True)

/tmp/ipykernel_161/3076638661.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['colorname'].fillna('unknown',inplace=True)

In [24]:
df.shape

(24714, 3)

In [25]:
df.isnull().sum()

name               0
fulldescription    0
colorname          0
dtype: int64

In [26]:
df['fulldescription'].str.len().describe()

count    24714.000000
mean      1047.272437
std        743.538204
min         37.000000
25%        617.000000
50%        817.000000
75%       1128.000000
max       5035.000000
Name: fulldescription, dtype: float64

replaced [] with NAN

dropped some columns

replaced NAN in colorname column with 'unknown'

check that the description column is long enough for training